# Generated by Django 4.0.5 on 2023-04-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_viewcount_remove_post_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
